export const Burger = () => {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
    >
      <line
        x1="4"
        y1="5"
        x2="20"
        y2="5"
        stroke="white"
        strokeWidth="2"
        strokeLinecap="round"
      />
      <line
        x1="4"
        y1="12"
        x2="20"
        y2="12"
        stroke="white"
        strokeWidth="2"
        strokeLinecap="round"
      />
      <line
        x1="4"
        y1="19"
        x2="20"
        y2="19"
        stroke="white"
        strokeWidth="2"
        strokeLinecap="round"
      />
    </svg>
  );
};
