import type { Metadata } from "next";
import "../styles/global.css";
import localFont from "next/font/local";
import { Header } from "@/components/layout/header/Header";
import { Footer } from "@/components/layout/footer/Footer";
import { Providers } from "@/state/Provider";
import Head from "next/head";

const myFont = localFont({
  src: [
    {
      path: "./fonts/THICCCBOI-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/THICCCBOI-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/THICCCBOI-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Gscore",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={myFont.className}>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </Head>
      <body>
        <Providers>
          <Header />
          <main>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
